{
    'name': "IT Asset Management",
    'summary': "Gestion de parc informatique pour prestataires IT",
    'description': """
Module pour gérer le parc informatique des clients, incluant équipements, contrats, 
incidents, interventions, licences, alertes et facturation récurrente.
    """,
    'author': "Your Name",
    'website': "http://www.yourwebsite.com",
    'category': 'Services',
    'version': '0.1',
    'depends': [
        'base',
        'mail',
        'account',
        'sale_subscription',
        'helpdesk',
        'stock',
        'portal',
        'web',
        'website',
        'auth_signup'
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'security/technician_access.xml',
        'data/auth_signup.xml',
        'data/sequence.xml',
        'data/category_data.xml',
        'data/equipment_type_data.xml',
        'data/journal_data.xml',
        'data/alert_cron.xml',
        'views/views.xml',
        'views/templates.xml',
        # Load views with actions first
        'views/client_views.xml',
        'views/equipment_views.xml',
        'views/contract_views.xml', 
        'views/category_views.xml',
        'views/incident_views.xml',
        'views/technicien_views.xml',  # Fichier de compatibilité (vide)
        'views/technician_views.xml',  # Nouveau modèle technicien
        'views/intervention_views.xml',
        'views/license_views.xml',
        'views/billing_views.xml',
        'views/alert_views.xml',
        'views/res_users_views.xml',
        # Then load menus that reference those actions
        'views/menus.xml',
        'views/portal_templates.xml',
        'views/portal_contracts.xml',
        'views/portal_subscriptions.xml',
        'views/portal_incidents.xml',
        'views/portal_invoices.xml',
        'report/contract_report.xml',
        'report/equipment_report.xml',
        'report/intervention_report.xml',
        'wizard/create_invoice.xml',
        'wizard/equipment_assignment.xml',
        'views/templates/auth_templates.xml',
        'views/templates/portal_login.xml',
        'views/templates/client_auth_form.xml',
        'views/templates/login_template.xml', 
        'views/templates/direct_signup.xml',
        'views/templates/client_welcome.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'it_asset_management/static/src/css/portal.css',
            'it_asset_management/static/src/js/portal.js',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'post_update_hook': 'post_update_hook',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}